CREATE TABLE `T_HOUSE` (
  `FID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FSOURCE_NAME` varchar(64) DEFAULT NULL COMMENT '来源',
  `FITEM_ID` varchar(64) NOT NULL COMMENT 'item ID',
  `FCITY` varchar(32) DEFAULT NULL COMMENT '城市',
  `FLOCATION` varchar(32) DEFAULT NULL COMMENT '地区',
  `FITEM_URL` varchar(128) DEFAULT NULL COMMENT '详情url',
  `FADDRESS` varchar(128) DEFAULT NULL COMMENT '详细地址',
  `FAREA_SIZE` float DEFAULT '0' COMMENT '建筑面积',
  `FPRICE` float DEFAULT '0' COMMENT '单价',
  `FMARKET_TOTAL_PRICE` float DEFAULT '0' COMMENT '市场总价',
  `FSELL_TOTAL_PRICE` float DEFAULT '0' COMMENT '成交总价',
  `FSELL_STATUS` varchar(32) DEFAULT NULL COMMENT '成交状态',
  `FSELL_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '成交时间',
  `FUPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `FCREATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '入库时间',
  PRIMARY KEY (`FID`),
  UNIQUE KEY `UDX_ITEM_ID` (`FITEM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
